version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # pull the swift-postal image
     - run: docker pull igormaka/swift-postal

     - run: docker run -v $(pwd):/code igormaka/swift-postal bash -c 'cd /code && swift test'
