version: 2
jobs:
 build:
   machine: true
   steps:
     - checkout
     # build the application image
     - run: docker build -t igormaka/swift-postal:$CIRCLE_BRANCH .

     - run: docker run -v $(pwd):/code igormaka/swift-postal:$CIRCLE_BRANCH bash -c 'cd /code && swift test'

     # deploy the image
    #  - run: docker push igormaka/swift-postal:$CIRCLE_BRANCH